#! /usr/bin/env bash

set -euxo pipefail

py_checks() {
    uv run ruff format .
    uv run ruff check --fix .
    uv run basedpyright .
    uv run pytest
}

precommit() {
    echo "Running pre-commit checks"
    root="$(git rev-parse --show-toplevel)"
    py_checks
}

(
    precommit
)
